# Generated by Django 5.1.7 on 2025-03-08 07:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DienVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên diễn viên')),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phim', models.CharField(max_length=200, verbose_name='Tên phim')),
                ('mo_ta', models.TextField(verbose_name='Mô tả phim')),
                ('dao_dien', models.CharField(max_length=200, verbose_name='Đạo diễn')),
                ('ngay_phat_hanh', models.DateField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('thoi_luong', models.PositiveIntegerField(help_text='Thời lượng phim tính bằng phút', verbose_name='Thời lượng')),
                ('anh_bia', models.ImageField(blank=True, null=True, upload_to='phim/anhbia/', verbose_name='Ảnh bìa')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='Trailer')),
                ('trang_thai', models.CharField(choices=[('sap_chieu', 'Sắp Chiếu'), ('dang_chieu', 'Đang Chiếu'), ('da_ket_thuc', 'Đã Kết Thúc')], default='sap_chieu', max_length=20, verbose_name='Trạng thái')),
                ('dien_vien', models.ManyToManyField(related_name='movies', to='myapp.dienvien', verbose_name='Diễn viên')),
                ('the_loai', models.ManyToManyField(related_name='movies', to='myapp.theloai', verbose_name='Thể loại')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='myapp_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='myapp_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LichSuXem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='myapp.movie', verbose_name='Phim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='myapp.user', verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm đánh giá')),
                ('binh_luan', models.TextField(verbose_name='Bình luận')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.movie', verbose_name='Phim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.user', verbose_name='Người dùng')),
            ],
            options={
                'unique_together': {('user', 'phim')},
            },
        ),
    ]
