# Generated by Django 5.1.7 on 2025-03-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theloai',
            options={'verbose_name_plural': 'Thể loại'},
        ),
    ]
