# Generated by Django 5.1.7 on 2025-03-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhgia',
            options={'ordering': ['-ngay_danh_gia']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-ngay_phat_hanh']},
        ),
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='user',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='danhgia',
            constraint=models.UniqueConstraint(fields=('user', 'phim'), name='unique_review_per_user'),
        ),
    ]
