# Generated by Django 5.1.7 on 2025-03-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_theloai_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
    ]
