# Generated by Django 5.1.7 on 2025-03-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapPhim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tap', models.PositiveIntegerField(verbose_name='Số tập')),
                ('ten_tap', models.CharField(max_length=200, verbose_name='Tên tập')),
                ('video', models.FileField(upload_to='phim/tapphim/', verbose_name='Video tập phim')),
                ('ngay_phat_hanh', models.DateField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='myapp.movie', verbose_name='Phim')),
            ],
            options={
                'ordering': ['so_tap'],
            },
        ),
    ]
