# Generated by Django 5.1 on 2025-03-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tapphim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TapPhim',
        ),
    ]
